#!/bin/bash
# SketchyBar color palette - generated by RiceKit
# source "$CONFIG_DIR/colors.sh" in your sketchybarrc

# Convert #RRGGBB to 0xffRRGGBB.
hex() { printf '0xff%s\n' "$(printf '%s' "$1" | cut -c 2-)"; }

# Color Definitions
COLOR_BACKGROUND=$(hex "{{background}}")
COLOR_FOREGROUND=$(hex "{{foreground}}")
COLOR_ACCENT=$(hex "{{accent}}")
COLOR_SELECTION=$(hex "{{accent}}")
COLOR_BORDER=$(hex "{{border}}")
export COLOR_BACKGROUND COLOR_FOREGROUND COLOR_ACCENT COLOR_SELECTION COLOR_BORDER

# Bar colors
BAR_COLOR=$(hex "{{background}}")
BAR_BORDER_COLOR=$(hex "{{border}}")
export BAR_COLOR BAR_BORDER_COLOR

# Item colors
ITEM_BG_COLOR=$(hex "{{accent}}")
ICON_COLOR=$(hex "{{accent}}")
LABEL_COLOR=$(hex "{{foreground}}")
export ITEM_BG_COLOR ICON_COLOR LABEL_COLOR

# ANSI colors
COLOR_BLACK=$(hex "{{black}}")
COLOR_RED=$(hex "{{red}}")
COLOR_GREEN=$(hex "{{green}}")
COLOR_YELLOW=$(hex "{{yellow}}")
COLOR_BLUE=$(hex "{{blue}}")
COLOR_MAGENTA=$(hex "{{magenta}}")
COLOR_CYAN=$(hex "{{cyan}}")
COLOR_WHITE=$(hex "{{white}}")
export COLOR_BLACK COLOR_RED COLOR_GREEN COLOR_YELLOW COLOR_BLUE COLOR_MAGENTA COLOR_CYAN COLOR_WHITE

# Bright ANSI colors
COLOR_BRIGHT_BLACK=$(hex "{{bright_black}}")
COLOR_BRIGHT_RED=$(hex "{{bright_red}}")
COLOR_BRIGHT_GREEN=$(hex "{{bright_green}}")
COLOR_BRIGHT_YELLOW=$(hex "{{bright_yellow}}")
COLOR_BRIGHT_BLUE=$(hex "{{bright_blue}}")
COLOR_BRIGHT_MAGENTA=$(hex "{{bright_magenta}}")
COLOR_BRIGHT_CYAN=$(hex "{{bright_cyan}}")
COLOR_BRIGHT_WHITE=$(hex "{{bright_white}}")
export COLOR_BRIGHT_BLACK COLOR_BRIGHT_RED COLOR_BRIGHT_GREEN COLOR_BRIGHT_YELLOW
export COLOR_BRIGHT_BLUE COLOR_BRIGHT_MAGENTA COLOR_BRIGHT_CYAN COLOR_BRIGHT_WHITE

# Transparent variants
COLOR_TRANSPARENT="0x80$(printf '%s' "$BAR_COLOR" | cut -c 5-)"
COLOR_SEMI_TRANSPARENT="0xcc$(printf '%s' "$BAR_COLOR" | cut -c 5-)"
export COLOR_TRANSPARENT COLOR_SEMI_TRANSPARENT
