#!/bin/bash
# SketchyBar color palette — generated by ricekit
# source "$CONFIG_DIR/colors.sh" in your sketchybarrc

# Convert #RRGGBB to 0xffRRGGBB
hex() { echo "0xff${1:1}"; }

# Color Definitions
export COLOR_BACKGROUND=$(hex "{{background}}")
export COLOR_FOREGROUND=$(hex "{{foreground}}")
export COLOR_ACCENT=$(hex "{{accent}}")
export COLOR_SELECTION=$(hex "{{accent}}")
export COLOR_BORDER=$(hex "{{border}}")

# Bar colors
export BAR_COLOR=$(hex "{{background}}")
export BAR_BORDER_COLOR=$(hex "{{border}}")

# Item colors
export ITEM_BG_COLOR=$(hex "{{accent}}")
export ICON_COLOR=$(hex "{{accent}}")
export LABEL_COLOR=$(hex "{{foreground}}")

# ANSI colors
export COLOR_BLACK=$(hex "{{black}}")
export COLOR_RED=$(hex "{{red}}")
export COLOR_GREEN=$(hex "{{green}}")
export COLOR_YELLOW=$(hex "{{yellow}}")
export COLOR_BLUE=$(hex "{{blue}}")
export COLOR_MAGENTA=$(hex "{{magenta}}")
export COLOR_CYAN=$(hex "{{cyan}}")
export COLOR_WHITE=$(hex "{{white}}")

# Bright ANSI colors
export COLOR_BRIGHT_BLACK=$(hex "{{bright_black}}")
export COLOR_BRIGHT_RED=$(hex "{{bright_red}}")
export COLOR_BRIGHT_GREEN=$(hex "{{bright_green}}")
export COLOR_BRIGHT_YELLOW=$(hex "{{bright_yellow}}")
export COLOR_BRIGHT_BLUE=$(hex "{{bright_blue}}")
export COLOR_BRIGHT_MAGENTA=$(hex "{{bright_magenta}}")
export COLOR_BRIGHT_CYAN=$(hex "{{bright_cyan}}")
export COLOR_BRIGHT_WHITE=$(hex "{{bright_white}}")

# Transparent variants
export COLOR_TRANSPARENT=$(echo "0x80${BAR_COLOR:4}")
export COLOR_SEMI_TRANSPARENT=$(echo "0xcc${BAR_COLOR:4}")
