// Generate a :root override CSS from the current ricekit theme.
//
// The output file is the same block the native-messaging host pushes to the
// Firefox addon at runtime — useful for:
//   - userContent.css @import
//   - nsIStyleSheetService.loadAndRegisterSheet (global user-origin sheet)
//   - a Stylus "apply to all sites" userstyle wrapping the :root block
import { generateRootCss, parseRicekitThemeShow } from "./palette.ts";

const themeName = Deno.args[0];
const outPath = Deno.args[1] ?? "./build/rk-vars.css";

if (!themeName) {
  console.error(
    "usage: deno run -A src/generate-vars.ts <theme-name> [output-path]",
  );
  Deno.exit(1);
}

const ricekitBin = Deno.env.get("RICEKIT_BIN") ??
  "/Users/parker/Documents/ricekit/target/debug/ricekit";

const { code, stdout, stderr } = await new Deno.Command(ricekitBin, {
  args: ["theme", "show", themeName],
  stdout: "piped",
  stderr: "piped",
}).output();

if (code !== 0) {
  console.error(`ricekit theme show failed:`);
  console.error(new TextDecoder().decode(stderr));
  Deno.exit(code);
}

const palette = parseRicekitThemeShow(new TextDecoder().decode(stdout));
const css = generateRootCss(
  palette,
  `/* generated by ricekit-community/userstyles from ricekit theme "${themeName}" */`,
);

await Deno.writeTextFile(outPath, css + "\n");
console.log(`wrote ${outPath}`);
