// Generate a :root override CSS from the current ricekit theme, writing
// values for all 26 Catppuccin tokens as CSS custom properties on :root.
// This CSS file is what our compiled userstyles read from — flipping any
// value here instantly re-themes every site.
//
// Output format is plain CSS (not a usercss), suitable for:
//   - userContent.css @import
//   - nsIStyleSheetService.loadAndRegisterSheet (global user-origin sheet)
//   - windowUtils.loadSheet(USER_SHEET) via the Ricekit Firefox addon
//   - a Stylus "apply to all sites" userstyle wrapping the :root block
import {
  CATPPUCCIN_TOKENS,
  mapRicekitToCatppuccin,
  parseRicekitThemeShow,
} from "./palette.ts";

const themeName = Deno.args[0];
const outPath = Deno.args[1] ?? "./build/ctp-vars.css";

if (!themeName) {
  console.error(
    "usage: deno run -A src/generate-vars.ts <theme-name> [output-path]",
  );
  Deno.exit(1);
}

const ricekitBin = Deno.env.get("RICEKIT_BIN") ??
  "/Users/parker/Documents/ricekit/target/debug/ricekit";

const { code, stdout, stderr } = await new Deno.Command(ricekitBin, {
  args: ["theme", "show", themeName],
  stdout: "piped",
  stderr: "piped",
}).output();

if (code !== 0) {
  console.error(`ricekit theme show failed:`);
  console.error(new TextDecoder().decode(stderr));
  Deno.exit(code);
}

const ricekit = parseRicekitThemeShow(new TextDecoder().decode(stdout));
const ctp = mapRicekitToCatppuccin(ricekit);

const lines: string[] = [
  `/* generated by ricekit-community/userstyles from ricekit theme "${themeName}" */`,
  `:root {`,
];
for (const t of CATPPUCCIN_TOKENS) {
  lines.push(`  --ctp-${t}: ${ctp[t]};`);
}
// Every userstyle's `@accent` also resolves to `var(--ctp-accent)` via our
// rewriter. Default the accent to ricekit's semantic accent color directly.
lines.push(`  --ctp-accent: ${ricekit.accent};`);
lines.push(`}`);

await Deno.writeTextFile(outPath, lines.join("\n") + "\n");
console.log(`wrote ${outPath} (${lines.length} lines)`);
