-- Ricekit generated colorscheme
-- Do not edit — regenerated on theme apply

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "ricekit"
vim.o.termguicolors = true

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Core UI
hi("Normal", { fg = "{{foreground}}", bg = "{{background}}" })
hi("NormalFloat", { fg = "{{foreground}}", bg = "{{surface}}" })
hi("FloatBorder", { fg = "{{border}}", bg = "{{surface}}" })
hi("CursorLine", { bg = "{{surface}}" })
hi("CursorColumn", { bg = "{{surface}}" })
hi("ColorColumn", { bg = "{{surface}}" })
hi("LineNr", { fg = "{{bright_black}}" })
hi("CursorLineNr", { fg = "{{accent}}", bold = true })
hi("SignColumn", { bg = "{{background}}" })
hi("FoldColumn", { fg = "{{bright_black}}", bg = "{{background}}" })
hi("Folded", { fg = "{{muted}}", bg = "{{surface}}" })

-- Selection & Search
hi("Visual", { bg = "{{blend(background, blue, 30%)}}" })
hi("VisualNOS", { bg = "{{blend(background, blue, 30%)}}" })
hi("Search", { fg = "{{background}}", bg = "{{yellow}}" })
hi("IncSearch", { fg = "{{background}}", bg = "{{accent}}" })
hi("CurSearch", { fg = "{{background}}", bg = "{{accent}}" })
hi("Substitute", { fg = "{{background}}", bg = "{{red}}" })

-- Status & Tab line
hi("StatusLine", { fg = "{{foreground}}", bg = "{{surface}}" })
hi("StatusLineNC", { fg = "{{muted}}", bg = "{{surface}}" })
hi("TabLine", { fg = "{{muted}}", bg = "{{surface}}" })
hi("TabLineFill", { bg = "{{surface}}" })
hi("TabLineSel", { fg = "{{foreground}}", bg = "{{background}}" })
hi("WinSeparator", { fg = "{{border}}" })

-- Popup menu
hi("Pmenu", { fg = "{{foreground}}", bg = "{{surface}}" })
hi("PmenuSel", { fg = "{{foreground}}", bg = "{{blend(background, accent, 30%)}}" })
hi("PmenuSbar", { bg = "{{surface}}" })
hi("PmenuThumb", { bg = "{{border}}" })

-- Messages
hi("ErrorMsg", { fg = "{{error}}" })
hi("WarningMsg", { fg = "{{warning}}" })
hi("MoreMsg", { fg = "{{info}}" })
hi("ModeMsg", { fg = "{{accent}}", bold = true })
hi("Question", { fg = "{{info}}" })
hi("Title", { fg = "{{accent}}", bold = true })
hi("Directory", { fg = "{{blue}}" })

-- Diff
hi("DiffAdd", { bg = "{{blend(background, green, 15%)}}" })
hi("DiffChange", { bg = "{{blend(background, yellow, 15%)}}" })
hi("DiffDelete", { fg = "{{red}}", bg = "{{blend(background, red, 10%)}}" })
hi("DiffText", { bg = "{{blend(background, yellow, 30%)}}" })

-- Diagnostics
hi("DiagnosticError", { fg = "{{error}}" })
hi("DiagnosticWarn", { fg = "{{warning}}" })
hi("DiagnosticInfo", { fg = "{{info}}" })
hi("DiagnosticHint", { fg = "{{cyan}}" })
hi("DiagnosticUnderlineError", { undercurl = true, sp = "{{error}}" })
hi("DiagnosticUnderlineWarn", { undercurl = true, sp = "{{warning}}" })
hi("DiagnosticUnderlineInfo", { undercurl = true, sp = "{{info}}" })
hi("DiagnosticUnderlineHint", { undercurl = true, sp = "{{cyan}}" })

-- Git signs
hi("GitSignsAdd", { fg = "{{green}}" })
hi("GitSignsChange", { fg = "{{yellow}}" })
hi("GitSignsDelete", { fg = "{{red}}" })

-- Syntax (standard Vim groups)
hi("Comment", { fg = "{{muted}}", italic = true })
hi("Constant", { fg = "{{cyan}}" })
hi("String", { fg = "{{green}}" })
hi("Character", { fg = "{{green}}" })
hi("Number", { fg = "{{magenta}}" })
hi("Boolean", { fg = "{{magenta}}" })
hi("Float", { fg = "{{magenta}}" })
hi("Identifier", { fg = "{{foreground}}" })
hi("Function", { fg = "{{blue}}" })
hi("Statement", { fg = "{{magenta}}" })
hi("Conditional", { fg = "{{magenta}}" })
hi("Repeat", { fg = "{{magenta}}" })
hi("Label", { fg = "{{cyan}}" })
hi("Operator", { fg = "{{foreground}}" })
hi("Keyword", { fg = "{{magenta}}" })
hi("Exception", { fg = "{{red}}" })
hi("PreProc", { fg = "{{cyan}}" })
hi("Include", { fg = "{{magenta}}" })
hi("Define", { fg = "{{magenta}}" })
hi("Macro", { fg = "{{cyan}}" })
hi("Type", { fg = "{{yellow}}" })
hi("StorageClass", { fg = "{{yellow}}" })
hi("Structure", { fg = "{{yellow}}" })
hi("Typedef", { fg = "{{yellow}}" })
hi("Special", { fg = "{{cyan}}" })
hi("SpecialChar", { fg = "{{cyan}}" })
hi("Tag", { fg = "{{accent}}" })
hi("Delimiter", { fg = "{{foreground}}" })
hi("SpecialComment", { fg = "{{muted}}" })
hi("Debug", { fg = "{{red}}" })
hi("Underlined", { underline = true })
hi("Error", { fg = "{{error}}" })
hi("Todo", { fg = "{{yellow}}", bold = true })

-- Treesitter
hi("@variable", { fg = "{{foreground}}" })
hi("@variable.builtin", { fg = "{{red}}" })
hi("@variable.parameter", { fg = "{{foreground}}", italic = true })
hi("@variable.member", { fg = "{{cyan}}" })
hi("@constant", { fg = "{{cyan}}" })
hi("@constant.builtin", { fg = "{{magenta}}" })
hi("@constant.macro", { fg = "{{cyan}}" })
hi("@module", { fg = "{{cyan}}" })
hi("@string", { fg = "{{green}}" })
hi("@string.escape", { fg = "{{cyan}}" })
hi("@string.regexp", { fg = "{{yellow}}" })
hi("@character", { fg = "{{green}}" })
hi("@number", { fg = "{{magenta}}" })
hi("@boolean", { fg = "{{magenta}}" })
hi("@float", { fg = "{{magenta}}" })
hi("@function", { fg = "{{blue}}" })
hi("@function.builtin", { fg = "{{blue}}" })
hi("@function.call", { fg = "{{blue}}" })
hi("@function.macro", { fg = "{{cyan}}" })
hi("@function.method", { fg = "{{blue}}" })
hi("@function.method.call", { fg = "{{blue}}" })
hi("@constructor", { fg = "{{yellow}}" })
hi("@operator", { fg = "{{foreground}}" })
hi("@keyword", { fg = "{{magenta}}" })
hi("@keyword.coroutine", { fg = "{{magenta}}" })
hi("@keyword.function", { fg = "{{magenta}}" })
hi("@keyword.operator", { fg = "{{magenta}}" })
hi("@keyword.import", { fg = "{{magenta}}" })
hi("@keyword.return", { fg = "{{magenta}}" })
hi("@keyword.conditional", { fg = "{{magenta}}" })
hi("@keyword.repeat", { fg = "{{magenta}}" })
hi("@keyword.exception", { fg = "{{red}}" })
hi("@type", { fg = "{{yellow}}" })
hi("@type.builtin", { fg = "{{yellow}}" })
hi("@type.qualifier", { fg = "{{magenta}}" })
hi("@attribute", { fg = "{{cyan}}" })
hi("@property", { fg = "{{cyan}}" })
hi("@comment", { fg = "{{muted}}", italic = true })
hi("@comment.todo", { fg = "{{yellow}}", bold = true })
hi("@comment.note", { fg = "{{info}}", bold = true })
hi("@comment.warning", { fg = "{{warning}}", bold = true })
hi("@comment.error", { fg = "{{error}}", bold = true })
hi("@punctuation.bracket", { fg = "{{foreground}}" })
hi("@punctuation.delimiter", { fg = "{{foreground}}" })
hi("@punctuation.special", { fg = "{{cyan}}" })
hi("@tag", { fg = "{{red}}" })
hi("@tag.attribute", { fg = "{{cyan}}" })
hi("@tag.delimiter", { fg = "{{foreground}}" })
hi("@markup.heading", { fg = "{{accent}}", bold = true })
hi("@markup.italic", { italic = true })
hi("@markup.strong", { bold = true })
hi("@markup.link", { fg = "{{blue}}", underline = true })
hi("@markup.link.url", { fg = "{{cyan}}", underline = true })
hi("@markup.raw", { fg = "{{green}}" })
hi("@markup.list", { fg = "{{magenta}}" })
