#!/bin/sh
# JankyBorders color configuration - generated by RiceKit

set -u

# Convert #RRGGBB to 0xffRRGGBB (ARGB format).
hex() { printf '0xff%s\n' "$(printf '%s' "$1" | cut -c 2-)"; }

ACTIVE_COLOR=$(hex "{{accent}}")
INACTIVE_COLOR=$(hex "{{border}}")
BORDER_WIDTH="5.0"

resolve_borders() {
  if [ -n "${RICEKIT_BORDERS_BIN:-}" ]; then
    if [ -x "$RICEKIT_BORDERS_BIN" ]; then
      printf '%s\n' "$RICEKIT_BORDERS_BIN"
      return 0
    fi
    return 1
  fi

  for candidate in /opt/homebrew/bin/borders /usr/local/bin/borders; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  command -v borders 2>/dev/null || return 1
}

run_bounded() {
  timeout_file="$(mktemp "${TMPDIR:-/tmp}/ricekit-command-timeout.XXXXXX")" || return 1
  rm -f "$timeout_file"
  "$@" >/dev/null 2>&1 &
  command_pid=$!
  (
    sleep 1
    : >"$timeout_file"
    kill -TERM "$command_pid" 2>/dev/null || exit 0
    sleep 1
    kill -KILL "$command_pid" 2>/dev/null || true
  ) &
  watchdog_pid=$!

  wait "$command_pid"
  command_status=$?
  kill "$watchdog_pid" 2>/dev/null || true
  wait "$watchdog_pid" 2>/dev/null || true
  if [ -e "$timeout_file" ]; then
    rm -f "$timeout_file"
    return 124
  fi
  rm -f "$timeout_file"
  return "$command_status"
}

BORDERS_BIN="$(resolve_borders)" || {
  echo "RiceKit: JankyBorders is unavailable. Install it with: brew install FelixKratz/formulae/borders" >&2
  exit 127
}

same_user_process_exists() {
  pgrep -U "$(id -u)" -x borders >/dev/null 2>&1
}

update_endpoint_exists() {
  launchctl print "gui/$(id -u)" 2>/dev/null | grep -Fq '"git.felix.borders"'
}

apply_border_style() {
  run_bounded "$BORDERS_BIN" \
    style=round \
    active_color="$ACTIVE_COLOR" \
    inactive_color="$INACTIVE_COLOR" \
    width="$BORDER_WIDTH"
}

if same_user_process_exists; then
  if ! update_endpoint_exists; then
    echo "RiceKit: a JankyBorders process exists but its update endpoint is unavailable. Stop it and apply the Rice again." >&2
    exit 1
  fi
  if apply_border_style; then
    exit 0
  fi
  echo "RiceKit: the running JankyBorders process did not accept the color update." >&2
  exit 1
fi

log_dir="$HOME/Library/Logs"
mkdir -p "$log_dir"
nohup "$BORDERS_BIN" \
  style=round \
  active_color="$ACTIVE_COLOR" \
  inactive_color="$INACTIVE_COLOR" \
  width="$BORDER_WIDTH" \
  >"$log_dir/RiceKit-jankyborders.log" 2>&1 &
started_pid=$!

attempt=0
endpoint_ready=0
while [ "$attempt" -lt 30 ]; do
  if ! kill -0 "$started_pid" 2>/dev/null; then
    wait "$started_pid"
    start_status=$?
    echo "RiceKit: JankyBorders exited during startup (status $start_status). See ~/Library/Logs/RiceKit-jankyborders.log." >&2
    exit 1
  fi
  if same_user_process_exists && update_endpoint_exists; then
    endpoint_ready=1
    break
  fi
  attempt=$((attempt + 1))
  sleep 0.1
done

if [ "$endpoint_ready" -eq 1 ]; then
  if apply_border_style; then
    exit 0
  fi
  kill "$started_pid" 2>/dev/null || true
  echo "RiceKit: the running JankyBorders process did not accept the color update." >&2
  exit 1
fi

kill "$started_pid" 2>/dev/null || true
echo "RiceKit: JankyBorders started but did not register its update endpoint within the readiness window. See ~/Library/Logs/RiceKit-jankyborders.log." >&2
exit 1
